# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build with Maven

on:
  workflow_dispatch:
     # inputs:
     #   publish_image:
     #     description: Publish Build Artifact
     #     type: boolean
     #     required: false
  push:
    branches: [ master, release/** ]

  #Trigger the workflow when a pull request is opened from the feature branch
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'master'
    paths:
      - '**'
      - '!.github/**'      # do not run on any change in this folder except this pipeline itself
      - '.github/workflows/maven-publish.yml'
      - '!**.md'           # do not run on doc change
      - '!src/main/resources/**.yaml'
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
